[package]
name = "jsonserde"
version = "0.1.0"
authors = ["Shoumik Palkar <shoumik@cs.stanford.edu>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
serde = { version = "1.0", features = ["derive"] }
